// Auto-generated by scripts/optimize-images.mjs - do not edit manually.

type ImageBlurEntry = {
  src: string;
  blurDataURL: string;
};

export const imageBlurData: Record<string, ImageBlurEntry> = {
  "/site-images/about-industrial-floor.webp?v=2": {
    src: "/site-images/about-industrial-floor.webp?v=2",
    blurDataURL: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoQAAwABUB8JaQAAv1lgI2eYAAA/rGGsIH00dvEHYgjMv4YqdOCZtZtYOpUkMxPAAA=",
  },
  "/site-images/about-inline-badge-industrial.webp?v=2": {
    src: "/site-images/about-inline-badge-industrial.webp?v=2",
    blurDataURL: "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAwABUB8JYgAAtzy/d6zOAD+39316kat8wIr+vi4XvKmYN6qOwENc7VX9Q3eJIym5ZcHr6I1u3FoAAA=",
  },
  "/site-images/carousel-cycle-control.webp?v=2": {
    src: "/site-images/carousel-cycle-control.webp?v=2",
    blurDataURL: "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoQAAwABUB8JQBdgBn7SuEQAADhwNFE42+rLLnea//rcDiWT7nM+T6+B3m+YAAA",
  },
  "/site-images/carousel-project-to-lot.webp?v=2": {
    src: "/site-images/carousel-project-to-lot.webp?v=2",
    blurDataURL: "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoQAAwABUB8JaQAAqEiYFgAANnfvqclKh3MKobIQtj+z68wAAA=",
  },
  "/site-images/carousel-technical-inspection.webp?v=2": {
    src: "/site-images/carousel-technical-inspection.webp?v=2",
    blurDataURL: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABwAQCdASoQAAwABUB8JaQAARRIAADieR0g3bTR+WkRHjjwDhx0SWQ8BOAJ6tvEJQLPkpQBF84/4TIhQwOKMAAA",
  },
  "/site-images/contact-form-industrial-line.webp": {
    src: "/site-images/contact-form-industrial-line.webp",
    blurDataURL: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAwABUB8JZQAAlLGDTLIAAD+SXA3PcixcvfHAOwVBbj0be2pUbIJL8nL7yKAfDPJmAYhEsWOLIaRfnJ2vqVAeAA=",
  },
  "/site-images/hero-quote-side-industrial.webp?v=2": {
    src: "/site-images/hero-quote-side-industrial.webp?v=2",
    blurDataURL: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAwABUB8JZwAArOvhE7kAAD+w94frvLdr5jZjQ7MNzwg+De8RdKWqTAiPdPm3ZfJNVVC2l5dYuodisVEIAAA",
  },
  "/site-images/proof-quality-molding-detail.webp?v=3": {
    src: "/site-images/proof-quality-molding-detail.webp?v=3",
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoQAAwABUB8JaQAAsSIgiSzX4AA/GZr9hACe/BvPCp/JzbG/JA40G1f+pKC5U/HeuC43MVgAAA=",
  },
  "/site-images/proof-support-operator-line.webp?v=3": {
    src: "/site-images/proof-support-operator-line.webp?v=3",
    blurDataURL: "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAwABUB8JaQAAuzTQJIrIAD80ye9f3mu1jbcp0+e6U3FzCNgGq8egAA=",
  },
  "/site-images/proof-technology-workbench.webp?v=3": {
    src: "/site-images/proof-technology-workbench.webp?v=3",
    blurDataURL: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAwABUB8JaQAAjc3oCLqwAD904AUVNQIZDoHhfvQqEySck6JQktnq6gC8tTYlJu/WAAA",
  },
  "/site-images/service-full-service-workflow.webp?v=2": {
    src: "/site-images/service-full-service-workflow.webp?v=2",
    blurDataURL: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAwABUB8JaQAAt11REK8AAD87w0YM0sV9ERdvCe27was+HikEalLE/ImF/uDsAtSVAAA",
  },
  "/site-images/service-outsourcing-detail.webp?v=2": {
    src: "/site-images/service-outsourcing-detail.webp?v=2",
    blurDataURL: "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACQAQCdASoQAAwABUB8JZwAAmrejGAA/pGTQySthZATDO7rC6A2kMFSWZWdTwmN4FI4oWmv53gAAA==",
  },
};
