// Auto-generated by scripts/optimize-images.mjs — do not edit manually.

type ImageBlurEntry = {
  src: string;
  blurDataURL: string;
};

export const imageBlurData: Record<string, ImageBlurEntry> = {
  "/site-images/about-industrial-floor.webp": {
    src: "/site-images/about-industrial-floor.webp",
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAAwABUB8JZQAAcTdlUvAAM4ykiIBkjYFu/FmJVyV9WDgEqSHxjgPlHKHgWY6m515Yj6LwzJ/wi4FzXaqJjpTjlkbK14EAAA=",
  },
  "/site-images/about-inline-badge-industrial.webp": {
    src: "/site-images/about-inline-badge-industrial.webp",
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAwABUB8JYwC7ACg+YjuWAAA/n39SdKvLHWb9g3kjR5Lm1mzUtfRdHA94ivJmdnNzzwAvcIpYt46XZW5mfJBU7uQB9wQAAA=",
  },
  "/site-images/carousel-cycle-control.webp": {
    src: "/site-images/carousel-cycle-control.webp",
    blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAwABUB8JYwAAv1/r4Y9vcAA/s3aq3lpHVN25DNzFKwwCMLseaQrOh8Ph50abTpZvHJveTHcjb4MW2LDTFVeFI2wJwZsLYWuceDcK8gIkAGcAAA=",
  },
  "/site-images/carousel-project-to-lot.webp": {
    src: "/site-images/carousel-project-to-lot.webp",
    blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAwABUB8JZwAAlxd6iTvAAD+qfIajSlmpXRlUvMvo33MK76Anuhqi0XiHFs6WWy52FIzM32SxoAuQCc0+HJeV4FAAA==",
  },
  "/site-images/carousel-technical-inspection.webp": {
    src: "/site-images/carousel-technical-inspection.webp",
    blurDataURL: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwABUB8JYgCsADdf6QTkQAA/rxS3tQf2P3jkkcxgJUEgdBTaLSYL5rzITm72WGF9VDAeXaRAB3uJi8cVXDw1IJKzpz33tpjANQifgAAAA==",
  },
  "/site-images/contact-form-industrial-line.webp": {
    src: "/site-images/contact-form-industrial-line.webp",
    blurDataURL: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAwABUB8JZQAAcQNgiPxAAD+SXAwjVmj1YFpeDOEh+/9DFtffbgz3gxQhBvXy1KGkd3KjD7GgnNyRUxj7PgTodewAAAA",
  },
  "/site-images/hero-quote-side-industrial.webp": {
    src: "/site-images/hero-quote-side-industrial.webp",
    blurDataURL: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoQAAwABUB8JQBOgBUs2iwAAP3vdw5ya1lEiKffiuQ6Z776xGeur88Y9JaX5K3XKzKRD0Y8x9e4V8ruH5qifq3b5pUpdrHuRQAAAA==",
  },
  "/site-images/proof-quality-molding-detail.webp": {
    src: "/site-images/proof-quality-molding-detail.webp",
    blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAAwABUB8JaQAAiBo0HkYAPAO2tM1iS0i5Tz0ZfqpKEGNhr15OiGW0PGd38HCJlYtseBVhS2tg0G9+7ON8IINmsIWkQoAAAA=",
  },
  "/site-images/proof-support-operator-line.webp": {
    src: "/site-images/proof-support-operator-line.webp",
    blurDataURL: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQAAwABUB8JYwAAqHh5SjuFUWwAP4y8s3E7tL4uqNNBXp5PzyYBRvwm+3IADX8vrUTLjA1+bnsJ5DonhDUCaO80AA=",
  },
  "/site-images/proof-technology-workbench.webp": {
    src: "/site-images/proof-technology-workbench.webp",
    blurDataURL: "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAQCdASoQAAwABUB8JZQAAlregIAA/qnMo7g77N57PFjqa4CrpIEe1JC67mIk9JQqdh6Zqlo/Rc4TszerS0zVqA8AAA==",
  },
  "/site-images/service-full-service-workflow.webp": {
    src: "/site-images/service-full-service-workflow.webp",
    blurDataURL: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAwABUB8JZwAAgbzTTJIAAD+P5bh1de4tzwgL9yUF7U1ApDFDOrYNwf/9SlCl5nnHaTKIfzV8mVupO0V/x5KQAA=",
  },
  "/site-images/service-outsourcing-detail.webp": {
    src: "/site-images/service-outsourcing-detail.webp",
    blurDataURL: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAwABUB8JZwC7ADoyKGlAAD1XBI++UYWiX4V1Z9pBSJQG+EFuWWngi5Yt7uCyF2o4sM6hsfUBAAA",
  },
};
