/**
 * Converts all PNG images in public/site-images/ to WebP (quality 82)
 * and generates blur placeholders for lib/image-blur-data.ts.
 *
 * Usage: node scripts/optimize-images.mjs
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const SITE_IMAGES_DIR = path.join(process.cwd(), 'public', 'site-images');
const BLUR_DATA_OUTPUT = path.join(process.cwd(), 'lib', 'image-blur-data.ts');
const WEBP_QUALITY = 82;
const BLUR_WIDTH = 16;
const BLUR_HEIGHT = 12;

async function main() {
  const files = await fs.readdir(SITE_IMAGES_DIR);
  const pngFiles = files.filter((f) => f.endsWith('.png'));

  if (pngFiles.length === 0) {
    console.log('No PNG files found in site-images/. Skipping conversion.');
    return;
  }

  console.log(`Found ${pngFiles.length} PNG files to convert.\n`);

  const blurEntries = [];

  for (const pngFile of pngFiles) {
    const inputPath = path.join(SITE_IMAGES_DIR, pngFile);
    const baseName = pngFile.replace(/\.png$/i, '');
    const webpFile = `${baseName}.webp`;
    const outputPath = path.join(SITE_IMAGES_DIR, webpFile);

    const inputStat = await fs.stat(inputPath);
    const inputKB = (inputStat.size / 1024).toFixed(0);

    // Convert to WebP
    await sharp(inputPath)
      .webp({ quality: WEBP_QUALITY })
      .toFile(outputPath);

    const outputStat = await fs.stat(outputPath);
    const outputKB = (outputStat.size / 1024).toFixed(0);
    const reduction = ((1 - outputStat.size / inputStat.size) * 100).toFixed(1);

    console.log(`  ${pngFile} (${inputKB} KB) → ${webpFile} (${outputKB} KB) — ${reduction}% smaller`);

    // Generate blur placeholder
    const blurBuffer = await sharp(inputPath)
      .resize(BLUR_WIDTH, BLUR_HEIGHT, { fit: 'cover' })
      .webp({ quality: 20 })
      .toBuffer();

    const blurDataURL = `data:image/webp;base64,${blurBuffer.toString('base64')}`;

    blurEntries.push({
      key: camelCase(baseName),
      publicPath: `/site-images/${webpFile}`,
      blurDataURL,
    });

    // Delete original PNG
    await fs.unlink(inputPath);
  }

  // Generate TypeScript file
  const tsLines = [
    '// Auto-generated by scripts/optimize-images.mjs — do not edit manually.',
    '',
    'type ImageBlurEntry = {',
    '  src: string;',
    '  blurDataURL: string;',
    '};',
    '',
    'export const imageBlurData: Record<string, ImageBlurEntry> = {',
  ];

  for (const entry of blurEntries) {
    tsLines.push(`  "${entry.publicPath}": {`);
    tsLines.push(`    src: "${entry.publicPath}",`);
    tsLines.push(`    blurDataURL: "${entry.blurDataURL}",`);
    tsLines.push('  },');
  }

  tsLines.push('};');
  tsLines.push('');

  await fs.writeFile(BLUR_DATA_OUTPUT, tsLines.join('\n'));

  console.log(`\nWrote blur data to ${BLUR_DATA_OUTPUT}`);
  console.log('Done. All PNGs converted to WebP and originals deleted.');
}

function camelCase(str) {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, char) => char.toUpperCase())
    .replace(/^[A-Z]/, (char) => char.toLowerCase());
}

try {
  await main();
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.error('Error:', message);
  process.exitCode = 1;
}
